// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "backend/models"

	mock "github.com/stretchr/testify/mock"
)

// LinkDriver is an autogenerated mock type for the LinkDriver type
type LinkDriver struct {
	mock.Mock
}

// DeleteLink provides a mock function with given fields: ID
func (_m *LinkDriver) DeleteLink(ID string) error {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLinkByID provides a mock function with given fields: ID
func (_m *LinkDriver) GetLinkByID(ID string) (*models.Link, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByID")
	}

	var r0 *models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Link, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Link); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLinksForMember provides a mock function with given fields: Email
func (_m *LinkDriver) GetLinksForMember(Email string) ([]*models.Link, error) {
	ret := _m.Called(Email)

	if len(ret) == 0 {
		panic("no return value specified for GetLinksForMember")
	}

	var r0 []*models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Link, error)); ok {
		return rf(Email)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Link); ok {
		r0 = rf(Email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQRsForMember provides a mock function with given fields: Email
func (_m *LinkDriver) GetQRsForMember(Email string) ([]*models.Link, error) {
	ret := _m.Called(Email)

	if len(ret) == 0 {
		panic("no return value specified for GetQRsForMember")
	}

	var r0 []*models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Link, error)); ok {
		return rf(Email)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Link); ok {
		r0 = rf(Email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertLink provides a mock function with given fields: Link
func (_m *LinkDriver) UpsertLink(Link *models.Link) error {
	ret := _m.Called(Link)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Link) error); ok {
		r0 = rf(Link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLinkDriver creates a new instance of LinkDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkDriver {
	mock := &LinkDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
