load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "member_driver",
    srcs = [
        "member_driver.go",
        "mongo_member_driver.go",
    ],
    importpath = "backend/drivers/member_driver",
    visibility = ["//visibility:public"],
    deps = [
        "//models",
        "@org_mongodb_go_mongo_driver//mongo",
        "@org_mongodb_go_mongo_driver//mongo/options",
    ],
)

go_test(
    name = "member_driver_test",
    srcs = ["mongo_member_driver_test.go"],
    embed = [":member_driver"],
    deps = [
        "//models",
        "@com_github_stretchr_testify//require",
        "@org_mongodb_go_mongo_driver//bson",
        "@org_mongodb_go_mongo_driver//mongo",
        "@org_mongodb_go_mongo_driver//mongo/integration/mtest",
    ],
)
