load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "helpers",
    srcs = ["helpers.go"],
    importpath = "backend/app_service/helpers",
    visibility = ["//visibility:public"],
    deps = [
        "//constants",
        "//models",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_skip2_go_qrcode//:go-qrcode",
    ],
)
