load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mocks",
    srcs = ["MemberDriver.go"],
    importpath = "backend/drivers/member_driver/mocks",
    visibility = ["//visibility:public"],
    deps = [
        "//models",
        "@com_github_stretchr_testify//mock",
    ],
)
