// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "backend/models"

	mock "github.com/stretchr/testify/mock"
)

// MemberDriver is an autogenerated mock type for the MemberDriver type
type MemberDriver struct {
	mock.Mock
}

// CountMembersWithEmail provides a mock function with given fields: Email
func (_m *MemberDriver) CountMembersWithEmail(Email string) (int, error) {
	ret := _m.Called(Email)

	if len(ret) == 0 {
		panic("no return value specified for CountMembersWithEmail")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(Email)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(Email)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMember provides a mock function with given fields: Email
func (_m *MemberDriver) DeleteMember(Email string) error {
	ret := _m.Called(Email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(Email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMemberByEmail provides a mock function with given fields: Email
func (_m *MemberDriver) GetMemberByEmail(Email string) (*models.Member, error) {
	ret := _m.Called(Email)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberByEmail")
	}

	var r0 *models.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Member, error)); ok {
		return rf(Email)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Member); ok {
		r0 = rf(Email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTokenForMember provides a mock function with given fields: Email, Token
func (_m *MemberDriver) SetTokenForMember(Email string, Token string) error {
	ret := _m.Called(Email, Token)

	if len(ret) == 0 {
		panic("no return value specified for SetTokenForMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(Email, Token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertMember provides a mock function with given fields: Member
func (_m *MemberDriver) UpsertMember(Member *models.Member) error {
	ret := _m.Called(Member)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Member) error); ok {
		r0 = rf(Member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMemberDriver creates a new instance of MemberDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberDriver {
	mock := &MemberDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
